In [10]:
#Importing the Dependencies 

In [11]:
#Loading the sklearn library load iris dataset
from sklearn.datasets import load_iris
#load the Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
#Loading Pandas
import pandas as pd
#Loading Numpy
import numpy as np
#Setting a random seed
np.random.seed(0)

In [12]:
#Creating a variable to store the iris_data
iris_data = load_iris() 
#Creating the Iris dataFrame with colums of iris feature Names
df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
#Looking at the first 5 rows of the dataset
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [38]:
#Creating a Test and Training the Data
df["flowerType"] = pd.Categorical.from_codes(iris_data.target, iris_data.target_names)
##df["flower type"] = pd.Categorical.from_codes(iris_data.target, iris_data.target_names)
##df["isTrained"] = np.random.uniform(0, 1, len(df)) <= .75
df = df.drop(["flowerType", "species"],axis=1)
#Viewing the first 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  flower type  isTrained  
0      setosa       True  
1      setosa       True  
2      setosa       True  
3      setosa       True  
4      setosa       True

In [34]:
#Creating separate dataFrames for both th training as well test data
train, test = df[df["isTrained"] == True], df[df["isTrained"] ==False]
#Prints the number of Training and testing observation datasets
print("Number of observations in the training data: ", len(train))
print("Number of observations in the testing data: ", len(test))

Number of observations in the training data:  118
Number of observations in the testing data:  32


In [36]:
#Create a list of the Iris feature Names 
features = df.columns[:4]
#View the features
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [42]:
#Converting the flower type names into digits i.e. zeros and 1s
y = pd.factorize(train["flower type"])[0] #Converts the flower type column into numerical values
#Training dataset 
print(train.head())
#Testing dataset
print(test.head())
#Viewing the target
y 


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species flower type  isTrained  
0  setosa      setosa       True  
1  setosa      setosa       True  
2  setosa      setosa       True  
3  setosa      setosa       True  
4  setosa      setosa       True  
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
7                 5.0               3.4                1.5               0.2   
8                 4.4               2.9                1.4               0.2   
10                5.4               3.7                1.5               0.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [43]:
#Initializes the Random Forest Classifier 
#n_jobs2 prioritizes the number of jobs to run when model is training, speeds up the training
#random_state controls the randomness of samples being used ensures that the data will be the same everytime the code is ran
clf = RandomForestClassifier(n_jobs=2, random_state=0)
#Trains the Classifier
#Creates the RandomForestClassifier fits the classifier with the features the input and y the target label the output
clf.fit(train[features], y) 

RandomForestClassifier(n_jobs=2, random_state=0)

In [45]:
#Applies the Classifier that was trained 
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [54]:
#Shows the predictions of first 12 probilities 
x_test = test[features] #Set variable x_test for test[features]
predicted_features = clf.predict_proba(x_test)[0:12]
predicted_features

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.95, 0.05, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ]])

In [60]:
#x_test contains the featured values 
predicted_classes = clf.predict(x_test) #Predicts the label of the class for the samples 
predicted_species = iris_data.target_names[predicted_classes] # maps the predicted class labels to the target names
#Shows the predicted flower types fror the observations
predicted_species[:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [62]:
#Actual flower types for first 5 observations
test["flower type"].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: flower type, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [66]:
#Creating a confusion matrix
pd.crosstab(test["flower type"], predicted_species, rownames=["Actual Flower Names"], colnames=["Predicted Flower Types"])

Predicted Flower Types  setosa  versicolor  virginica
Actual Flower Names                                  
setosa                      13           0          0
versicolor                   0           5          2
virginica                    0           0         12

In [71]:
#Predictiing the flower Types at the given measurements
predicted_species = iris_data.target_names[clf.predict([[5.0, 3.6, 1.4, 2.0],[5.5 ,2.7, 1.1, 2.2]])] 
print("The preditced flower Types at these values are:", predicted_species)

The preditced flower Types at these values are: ['setosa' 'setosa']


C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
